In [1]:
import os

In [2]:
os.chdir("../")

In [3]:
from deep_game.models import *

In [4]:
board = Board()

In [5]:
board.state

{'alive': True,
 'circles': [{'id': 0, 'x': 292.25974069960165, 'y': 173.05804165164477}],
 'dots': [{'id': 0, 'x': 15.46629342211494, 'y': 378.17820388365686},
  {'id': 1, 'x': 37.17934356328525, 'y': 278.9252292389523},
  {'id': 2, 'x': 434.08553642374915, 'y': 233.36013502279621},
  {'id': 3, 'x': 82.58413546281535, 'y': 253.29333383485832},
  {'id': 4, 'x': 155.249931446829, 'y': 177.95524294273676},
  {'id': 5, 'x': 344.60186987776416, 'y': 147.297959119635},
  {'id': 6, 'x': 38.76382904334279, 'y': 109.84925276826102},
  {'id': 7, 'x': 525.3973427286463, 'y': 390.26715342677704},
  {'id': 8, 'x': 78.28885621924093, 'y': 203.93186995869704},
  {'id': 9, 'x': 412.7803944410713, 'y': 368.99752879614925}],
 'score': 0,
 'triangles': [{'id': 0, 'x': 249.46575779777805, 'y': 214.95438125158287},
  {'id': 1, 'x': 391.46704395251714, 'y': 48.836229447059495}]}

In [8]:
class Interface(object):
    
    def __init__(self, board):
        self._board = board
        
    @property
    def state(self):
        state = self._board.state
        x = np.zeros((21,2))
        points = state['circles'] + state['dots'] + state['triangles']
        for i, p in enumerate(points):
            x[i, 0] = p['x']
            x[i, 1] = p['y']
        return x

99

In [12]:
x = np.array([-1, 101])

In [13]:
x

array([ -1, 101])

In [15]:
x % [100, 99]

array([99,  2])

In [19]:
import numpy as np

In [20]:
theta = 15

In [21]:
phi = theta / 360. * 2 * np.pi

In [22]:
sin = np.sin(phi)

In [23]:
cos = np.cos(phi)

In [24]:
sin

0.25881904510252074

In [25]:
cos

0.96592582628906831

In [28]:
r = np.array([[cos, -sin], [sin, cos]])

In [32]:
pos = np.array([0,1])

In [33]:
np.dot(pos, r)

array([ 0.25881905,  0.96592583])