In [1]:
import numpy as np

In [3]:
x = np.array([[1,2],
              [2,3]])

In [5]:
x * [100, 200]

array([[100, 400],
       [200, 600]])

In [6]:
np.random.rand(20, 2)

array([[ 0.63007158,  0.69744946],
       [ 0.77891664,  0.84868981],
       [ 0.89067962,  0.8592036 ],
       [ 0.87919036,  0.72044006],
       [ 0.58066314,  0.41111204],
       [ 0.22428219,  0.96587612],
       [ 0.91164756,  0.31746829],
       [ 0.25607858,  0.37705423],
       [ 0.65551575,  0.91347858],
       [ 0.26684104,  0.5025009 ],
       [ 0.18680905,  0.27074638],
       [ 0.85992276,  0.74451118],
       [ 0.4224254 ,  0.55421208],
       [ 0.54712529,  0.70431062],
       [ 0.49085751,  0.54887513],
       [ 0.6247731 ,  0.86816501],
       [ 0.24185071,  0.73741057],
       [ 0.52136767,  0.38725208],
       [ 0.2544816 ,  0.78380152],
       [ 0.47213384,  0.41406041]])

In [9]:
x = np.array([99,105, -5])

In [11]:
105 % 100

5

In [12]:
-5 % 100

95

In [13]:
100 - (105 - 100)

95

In [14]:
x = np.array([[101, 201], [99, 199]])

In [15]:
x > [100, 200]

array([[ True,  True],
       [False, False]], dtype=bool)

In [19]:
r = np.array([[1,2,3]])

In [23]:
r.shape

(1, 3)

In [21]:
r + r.T

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [24]:
r = np.array(range(3))

In [25]:
r

array([0, 1, 2])

In [27]:
r2 = r.reshape(1, -1)

In [28]:
r2

array([[0, 1, 2]])

In [29]:
r2 + r2.T

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [32]:
x = np.array([[1,2],[2,3], [3,4]])

In [33]:
x

array([[1, 2],
       [2, 3],
       [3, 4]])

In [35]:
from scipy.spatial.distance import pdist

In [36]:
pdist(x)

array([ 1.41421356,  2.82842712,  1.41421356])

In [49]:
dist = np.sqrt((np.square(x[:, np.newaxis]-x).sum(axis=2)))

In [51]:
collisions = dist > 1.5

In [52]:
np.where(collisions)

(array([0, 2]), array([2, 0]))

2.8284271247461903